import PDFDocument from 'pdfkit';
import { ApiError } from '../utils/ApiError';
import { format } from '../utils/format';
import { getOperation } from './operation.service';

const TYPE_TITLE: Record<string, string> = {
  receipt: 'Receipt',
  delivery: 'Delivery Order',
  internal: 'Internal Transfer',
  adjustment: 'Inventory Adjustment',
};

interface Named {
  name?: string;
  fullName?: string;
  loginId?: string;
  shortCode?: string;
}
interface LineProduct {
  sku?: string;
  name?: string;
  uom?: string;
}

/** Renders a Done operation as an A4 PDF. Anything not Done → 409. */
export async function renderOperationPdf(id: string): Promise<{ buffer: Buffer; filename: string }> {
  const op = await getOperation(id);
  if (op.status !== 'done') throw ApiError.conflict('Print is available once the operation is Done');

  const doc = new PDFDocument({ size: 'A4', margin: 48, info: { Title: op.reference, Author: 'StockSense' } });
  const chunks: Buffer[] = [];
  doc.on('data', (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));

  const indigo = '#4F46E5';
  const muted = '#6B7280';
  const left = 48;
  const width = doc.page.width - 96;

  // Header band
  doc.rect(0, 0, doc.page.width, 6).fill(indigo);
  doc.fillColor('#111827').font('Helvetica-Bold').fontSize(20).text('StockSense', left, 36);
  doc.font('Helvetica').fontSize(9).fillColor(muted).text('Inventory, in real time.', left, 60);
  doc.font('Helvetica-Bold').fontSize(11).fillColor(indigo).text(TYPE_TITLE[op.type] ?? op.type, left, 36, { width, align: 'right' });
  doc.font('Courier-Bold').fontSize(16).fillColor('#111827').text(op.reference, left, 52, { width, align: 'right' });

  doc.moveTo(left, 88).lineTo(left + width, 88).lineWidth(0.5).strokeColor('#E5E7EB').stroke();

  // Details grid
  const contact = op.contact as Named | null;
  const from = op.sourceLocation as Named | null;
  const to = op.destinationLocation as Named | null;
  const responsible = op.responsible as Named | null;
  const details: [string, string][] = [
    ['Operation type', TYPE_TITLE[op.type] ?? op.type],
    ['Status', 'Done'],
    ['Scheduled', format.date(op.scheduleDate)],
    ['Done on', format.dateTime(op.doneDate)],
    ['From', from?.fullName ?? '—'],
    ['To', to?.fullName ?? '—'],
    ['Contact', contact?.name ?? '—'],
    ['Responsible', responsible?.name || responsible?.loginId || '—'],
  ];
  if (op.type === 'delivery' && op.deliveryAddress) details.push(['Delivery address', op.deliveryAddress]);
  if (op.type === 'adjustment' && op.reason) details.push(['Reason', op.reason.replace('_', ' ')]);

  let y = 104;
  const colW = width / 2;
  details.forEach(([label, value], i) => {
    const x = left + (i % 2) * colW;
    if (i % 2 === 0 && i > 0) y += 34;
    doc.font('Helvetica').fontSize(8).fillColor(muted).text(label.toUpperCase(), x, y, { width: colW - 12, characterSpacing: 0.5 });
    doc.font('Helvetica').fontSize(11).fillColor('#111827').text(value, x, y + 11, { width: colW - 12 });
  });
  y += 52;

  // Products table
  doc.roundedRect(left, y, width, 24, 4).fill('#F3F4F6');
  doc.font('Helvetica-Bold').fontSize(9).fillColor('#374151');
  doc.text('PRODUCT', left + 10, y + 8);
  doc.text('UOM', left + width - 170, y + 8, { width: 60 });
  doc.text('QUANTITY', left + width - 100, y + 8, { width: 90, align: 'right' });
  y += 32;

  let total = 0;
  doc.font('Helvetica').fontSize(10).fillColor('#111827');
  for (const line of op.lines) {
    const p = line.product as unknown as LineProduct | null;
    const qty = line.doneQty || line.quantity;
    total += qty;
    if (y > doc.page.height - 120) {
      doc.addPage();
      y = 48;
    }
    doc.font('Courier').fontSize(9).fillColor(indigo).text(`[${p?.sku ?? '—'}]`, left + 10, y, { continued: true });
    doc.font('Helvetica').fontSize(10).fillColor('#111827').text(` ${p?.name ?? 'Deleted product'}`);
    doc.text(p?.uom ?? '', left + width - 170, y, { width: 60 });
    doc.font('Helvetica-Bold').text(format.number(qty), left + width - 100, y, { width: 90, align: 'right' });
    y += 22;
    doc.moveTo(left, y - 6).lineTo(left + width, y - 6).lineWidth(0.5).strokeColor('#F3F4F6').stroke();
  }

  y += 6;
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#111827').text(`Total quantity: ${format.number(total)}`, left, y, { width, align: 'right' });

  doc.font('Helvetica').fontSize(8).fillColor(muted).text(`Generated by StockSense on ${format.dateTime(new Date())}`, left, doc.page.height - 60, { width, align: 'center' });

  doc.end();
  return { buffer: await done, filename: `${op.reference.replace(/\//g, '-')}.pdf` };
}
